### PR TITLE
fix crash with 2.5

### PR DESCRIPTION
**Pull request by kaisomir**

### CODE REVIEW

**Comment by kaisomir** [comment]
I originally created this PR to try and fix a crash I was having with 1.19.2 (Fabric 14.9, Fabric API 0.59.0+1.19.2, Litematica 0.12.3 for 1.19.2, MaLiLib 0.13.0), but even after changing these properties it still crashes. Crash report is in the attached file, will also submit and link an issue in a moment.

[litematica_builder_crash.txt](https://github.com/aleksilassila/litematica-printer/files/9295949/litematica_builder_crash.txt)

**Comment by kaisomir** [comment]
Nevermind, looking into the crash further showed that it had to do with the didCheckForUpdates field. Making it private fixes my crash, committed, and works in-game.

**Comment by kaisomir** [comment]
Since someone linked to this PR in an issue, here's my compiled version for anyone that needs it :)

[litematica-printer-1.19.2-2.5.zip](https://github.com/aleksilassila/litematica-printer/files/9301847/litematica-printer-1.19.2-2.5.zip)

**Comment by aleksilassila** [comment]
Uh, I hate it when the ide doesn't catch these mixin issues. Thank you

**Pull request merged**
