### PR TITLE
Update to 1.19.4 + Upgrade gradle wrapper

### PR DESCRIPTION
**Pull request by o0sh4d0w0o**
## Description

Update litematica-printer to lastest minecraft version (1.19.4)

### CODE REVIEW

**Comment by aleksilassila** [comment]
MVP, I'll look through it this weekend

**Comment by o0sh4d0w0o** [comment]
> MVP, I'll look through it this weekend

Currently, it's updated to the 1.19.4 version and build successfully, but it looks like print functionality don't work anymore, probably due from new behavior somewhere, need some investigation to make it work as before.

**Comment by aleksilassila** [comment]
@o0sh4d0w0o would you let me know when this is ready to merge

**Comment by o0sh4d0w0o** [comment]
> @o0sh4d0w0o would you let me know when this is ready to merge and if you need help with synchronizing the implementations

Seems all is ready to merge, i built it successfully and tested it ingame without any problems with a big schematic.

**Pull request merged**
