### PR TITLE
Create a build

### PR DESCRIPTION
**Pull request by Johannes7k75**
I created a Github action that builds a new version on every commit.
To get the latest build (when the code is updated) as a normal user.

### CODE REVIEW

**Comment by aleksilassila** [comment]
Looks good! Does this also work on 1.17 branch (and possibly 1.16 too), or only 1.18 right now? I don't have time to tinker with those right now, I'm wondering if it would be possible to do builds on multiple branches, too?

**Comment by Johannes7k75** [comment]
just works currently on the main branch so just 1.18.
But I could make it run on multiple branches

**Comment by Johannes7k75** [comment]
Should work on 1.18, 1.17 and 1.16 but for 1.15 there has to be something chabged.

**Comment by Johannes7k75** [comment]
Hmm the 1.15 branch seems to have a issue with modMenu and fails.

**Comment by aleksilassila** [comment]
Looks great, will test and merge this next weekend when I get back home. I don't update 1.15 anyway so won't be needing support for that

**Pull request merged**
